version: '3.8'

services:
  email-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    ports:
      - "9229:9229"  # Debug port
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
